'use strict';
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const compression = require('compression');
const rateLimit = require('express-rate-limit');
const logger = require('./utils/logger');
const errorHandler = require('./middleware/errorHandler');
const requestLogger = require('./middleware/requestLogger');
const analyzeRoutes = require('./routes/analyze');
const trendingRoutes = require('./routes/trending');
const searchRoutes = require('./routes/search');
const downloadRoutes = require('./routes/download');
const healthRoutes = require('./routes/health');
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.CORS_ORIGIN || '*', methods: ['GET','POST','PUT','DELETE','OPTIONS'] }));
app.use(compression());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
if (process.env.NODE_ENV !== 'test') {
  app.use(morgan('combined', { stream: { write: (m) => logger.info(m.trim()) } }));
}
app.use(requestLogger);
const globalLimiter = rateLimit({ windowMs: 15*60*1000, max: 100, standardHeaders: true, legacyHeaders: false });
app.use('/api/', globalLimiter);
const analyzeLimiter = rateLimit({ windowMs: 60*1000, max: 20 });
app.use('/api/v1/health', healthRoutes);
app.use('/api/v1/analyze', analyzeLimiter, analyzeRoutes);
app.use('/api/v1/trending', trendingRoutes);
app.use('/api/v1/search', searchRoutes);
app.use('/api/v1/download', downloadRoutes);
app.use((req, res) => res.status(404).json({ success: false, error: 'Not found', path: req.path }));
app.use(errorHandler);
module.exports = app;
